{
 "title": "Nubox Alerts",
 "tags": [
  "Prometheus",
  "windows_exporter"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage (%)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (job) (irate(windows_cpu_time_total{mode=\"idle\"}[2m])) * 100) > 75"
    }
   ]
  },
  {
   "title": "Ram Memory Usage (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100.0 - (100 * avg by (job) (windows_os_physical_memory_free_bytes / windows_cs_physical_memory_bytes)) > 85"
    }
   ]
  },
  {
   "title": "Disk Usage (%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100.0 - 100 * (windows_logical_disk_free_bytes / windows_logical_disk_size_bytes) > 80"
    }
   ]
  }
 ]
}